export const sidebarItems=[
    {
        link:"/admin",
        title:"Dashboard",
        id:1
    },
    {
        link:"/admin/users",
        title:"Users",
        id:2
    },
    {
        link:"/admin/books",
        title:"Books",
        id:3
    },
    {
        link:"/admin/favourites",
        title:"Favourites",
        id:4
    },
    {
        link:"/admin/baskets",
        title:"Baskets",
        id:5
    },
]